# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Lauren Kwon
title: ê¶Œìˆ˜í˜„ æƒç§€è´¤
email: sk7905@nyu.edu
# email_title: Email (Email title override)
#phone: +82 10-6624-0177
# phone_title: Phone (Phone title override)
website: https://skwon017.github.io
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: kwon00_
github_username:  skwon017
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: kwonsoohyun
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
orcid_username: 0000-0003-1277-0849
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
#additional_links:
#- title: Link name
  #icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  #url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/DSC00420.JPG
about_content: | # this will include new lines to allow paragraphs
  
  
  
  LovingðŸ¥°
  
  AmbitiousðŸ¤©
  
  UnderstandingðŸ˜Œ
  
  ResponsibleðŸ¤
  
  EncouragingðŸ¤—
  
  NoteworthyðŸ˜Ž


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Project name
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          
  - title: Experience
    layout: list
    content:
      - layout: left
        border: weak
        title: Human-Centered Artificial Intelligence Lab (HCAIL)
        sub_title: Research Intern
        caption: May 2022 - Present
        link: https://hcail.uos.ac.kr
        quote: >
          Research group in the Department of Computer Science and Engineering at the University of Seoul. Explores Human-Computer Interaction.
        description: | # this will include new lines to allow paragraphs
          
      - layout: left
        title: Give Orange New York (GIVO)
        sub_title: Research & Development Director
        caption: Sep 2019 - May 2022
        link: https://www.givorange.com
        quote: >
          Non-profit donation organization led by international students. Aims to establish a healthy donation culture in Korean society.
        description: | # this will include new lines to allow paragraphs
          
  - title: Education
    layout: list
    content:
      - layout: top-left
        title: New York University
        sub_title: Psychology and Data Science
        caption: Sep 2019 -  Dec 2023
        quote: >
          Private institution founded in 1831. Embraces diversity and ensures wide range of perspectives at one of the most dynamic cities in the world.
        description: | # this will include new lines to allow paragraphs
          
  - title: Skills
    layout: text
    content: |
        Programming Languages: <mark>python</mark> <mark>Java</mark>
      
        Natural Languages: <mark>English</mark> <mark>Korean</mark> <mark>Mandarin</mark>

      
      
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
